# Stage 1: Build the app
FROM node:18 AS build-stage

WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

RUN npm install

# Copy all source code
COPY . .

# Build the app in production mode
RUN npm run build -- --prod

# Stage 2: Serve the app with Nginx
FROM nginx:alpine AS production-stage

# Copy compiled files from build stage
COPY --from=build-stage /app/dist/desafio-pokemon /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Default command to run Nginx
CMD ["nginx", "-g", "daemon off;"]
